Exit after compilation when syntax errors occurred (closes #280)
cksystemsteaching/selfie pull request #285
Opened 2021-05-27 22:03 UTC by Blazefrost

This pull request introduces the EXITCODE_SYNTAXERROR (and also adds a missing exit code to the grader).

Previously, Selfie exited on non-recoverable syntax errors (e.g. EXITCODE_SCANNERERROR for unknown escape sequences, EXITCODE_PARSERERROR for undeclared variables or EXITCODE_COMPILERERROR if there are no temporary registers left). However, it silently continued on recoverable syntax errors, treating them more like warnings.

This commit introduces the counter `number_of_syntax_errors` which shall be incremented each time a syntax error was encountered. After compilation, Selfie checks the syntax error counter and exits with a message before the binary is written to the disk if there actually were syntax.
Because compilation is still not immediately stopped after encountering a recoverable syntax error, it is still possible to enumerate all syntax errors of a file.

2021-05-28 09:26 UTC, ckirsch requested changes
@Blazefrost Thanks a lot! See my comments on two tiny issues.

2021-05-28 12:59 UTC, ckirsch requested changes

2021-05-30 01:10 UTC, Blazefrost commented on grader/assignments/fork-wait/sum-exit-code.c
> +    *(sorted_numbers + i) = i*2;
I've explained the changes on the grader more detailed in commit 463762a.

In summary, the grader's test suite makes sure that no exit codes of any checks collide with any of Selfie's exit codes. By adding `EXITCODE_SYNTAXERROR` (and another exit code that has not been added to the grader yet), the old return value of the `sum-exit-code` would collide with `EXITCODE_MODELINGERROR`. I've fixed this by doubling the exit code.

2021-05-30 01:15 UTC, Blazefrost commented on selfie.c
> +uint64_t number_of_syntax_errors = 0; // the number of encountered syntax error
Done!

2021-05-30 01:15 UTC, Blazefrost commented on selfie.c
> +      number_of_syntax_errors = 0;
Done!

2021-05-31 07:16 UTC, merged

2021-05-31 08:14 UTC, ckirsch commented
@Blazefrost I merged your code into the branch `elementary-computer-science`. Could you please check if your changes here work there as well? In particular, I moved the exit codes for symbolic execution and modeling into the engine and modeler...

2021-05-31 11:30 UTC, Blazefrost commented
I tested it on `elementary-computer-science` and it does work fine!