Showcase the use of expect_symbol as mentioned in the lecture.
cksystemsteaching/selfie pull request #318
Opened 2022-05-11 15:38 UTC by user-0xcafe

As I mentioned in the lecture today, the use of `expect_symbol`,
instead of the 4 lines that it replaces, can more clearly communicate 
what is happening in the code.

I am curious what you think about it @ckirsch.

2022-05-11 16:11 UTC, ckirsch commented
@user-0xcafe Very nice! Please go ahead and apply that everywhere. I will then pull that in after the current assignment.

2022-05-11 18:19 UTC, nbes4 commented
Little bit of nitpicking here, but since this addition is meant for more code clarity, would it make sense to rename `expect_symbol` to something like `expect_symbol_and_get()`, `expect_and_get_symbol()` or `expect_symbol_and_consume()` etc? Since, especially for "newcomers", `expect_symbol()` sounds more like a check, but it eventually consumes the current symbol and moves on to the next.

Any opinions on this?
Otherwise, great addition 👍

2022-05-12 06:03 UTC, user-0xcafe commented
Great question. I do like the some of your suggestions, especially those that read almost like sentences. 

One reason I didnt use a longer name as that I wanted to mimic `get_symbol`.

The other reason is that all of those names only tell half the story. They do not talk about emitting an error if the symbols do not match. I thought thet this mignt be more confusing. 

But I am happy to change it to `expect_and_get_symbol` if you think that I am overthinking this.

2022-05-12 07:21 UTC, nbes4 commented
I understand your concerns and the goal to mimic `get_symbol`. In the meantime the name `expect_symbol()` kind of implies that it can fail if we get something that we not "expect", so adding `and_get` would surely be a small bonus for clarity. However, this is just my subjective thinking, so please make sure you name the function as you see fit.

2022-05-12 17:09 UTC, ckirsch commented
> I believe that with the second commit I converted all the “low-hanging fruits”. There is a slight variation of the theme that I didn't touch: when the parser exits on a syntax error.

How about another procedure for this case? How often does it occur? How about `force_symbol()` for that?

2022-05-12 18:16 UTC, user-0xcafe commented
@ckirsch I just implemented that in the third commit. 

@nbes4 Another possible name that I considered are `get_expected_symbol` and `get_required_symbol`. I would like to get your opinion on those.

2022-05-13 08:11 UTC, ckirsch commented
> @ckirsch I just implemented that in the third commit.
> 
> @nbes4 Another possible name that I considered are `get_expected_symbol` and `get_required_symbol`. I would like to get your opinion on those.

@user-0xcafe Nice! Please use those names instead.

2022-05-13 08:55 UTC, nbes4 commented
`get_expected_symbol `and `get_required_symbol` seem like a good and clear choice!

2022-05-14 12:26 UTC, user-0xcafe commented
@ckirsch I changed the names and am very pleased with the way it reads. 
@nbes4 Thanks for your input!

2022-05-14 12:33 UTC, ckirsch requested changes
@user-0xcafe great work! please fix the remaining issues, I will then pull.

2022-05-14 12:33 UTC, ckirsch commented on selfie.c
> +void get_required_symbol(uint64_t expected_symbol);
`expected_symbol` -> `required_symbol`

2022-05-14 12:33 UTC, ckirsch commented on selfie.c
> +void get_required_symbol(uint64_t expected_symbol) {
call `get_expected_symbol()` here but with a return value that indicates an error on which you then exit.

2022-05-14 12:33 UTC, ckirsch commented on selfie.c
> +}
no trailing empty line please

2022-05-15 17:34 UTC, ckirsch requested changes

2022-05-15 17:34 UTC, ckirsch commented on selfie.c
> +    found = 1;
Just `return 1` here, no need for `found`.

2022-05-18 07:02 UTC, merged